---
- name: Check LOCALE After Update
  command: locale
  register: locale02
#- name: Show Locale After Update
#  debug:
#        var: locale02.stdout_lines
- local_action: "copy content={{ locale02.stdout }} dest=/home/ec2-user/{{ansible_host}}_local02.txt user=ec2-user group=ec2-user mode='0644'"