---
- name: Check Process 
  shell: ps -eo command --sort comm | grep -v COMMAND
  register: checkproc01
- local_action: "copy content={{ checkproc01.stdout }} dest=/home/ec2-user/{{ansible_host}}_proc01.txt user=ec2-user group=ec2-user mode='0644'"