---
- name: Check needs-restarting command after reboot
  shell: needs-restarting -r
  register: need02
  ignore_errors: yes
#- name: Show Info needs-restarting command after reboot
#  debug:
#        var: need02.stdout_lines
- local_action: "copy content={{ need02.stdout }} dest=/home/ec2-user/{{ansible_host}}_need02.txt user=ec2-user group=ec2-user mode='0644'"