---
- name: Check needs-restarting command
  shell: needs-restarting -r
  register: need01
  ignore_errors: yes
#- name: Show Info needs-restarting command
#  debug:
#        var: need01.stdout_lines
- local_action: "copy content={{ need01.stdout }} dest=/home/ec2-user/{{ansible_host}}_need01.txt user=ec2-user group=ec2-user mode='0644'"