---
- name: Check LOCALE
  command: locale
  register: locale01
# - name: Show Locale
#  debug:
#        var: locale01.stdout_lines
- local_action: "copy content={{ locale01.stdout }} dest=/home/ec2-user/{{ansible_host}}_local01.txt user=ec2-user group=ec2-user mode='0644'"