---
- name: Install Updates
  shell: yum update -y
  register: yum_update
#- name: Show Info Process Updates
#  debug:
#        var: yum_update.stdout_lines
- local_action: "copy content={{ yum_update.stdout }} dest=/home/ec2-user/{{ansible_host}}_update.txt user=ec2-user group=ec2-user mode='0644'"